# Generated by Django 5.1.5 on 2026-08-14 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zikr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arabic_text', models.CharField(max_length=500)),
                ('transliteration', models.CharField(help_text='Masalan: Laa ilaaha illalloh', max_length=255)),
                ('translation', models.CharField(help_text="Masalan: Allohdan o'zga iloh yo'q", max_length=500)),
                ('target_count', models.PositiveBigIntegerField()),
                ('current_count', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserZikrCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zikr_counts', to=settings.AUTH_USER_MODEL)),
                ('zikr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_counts', to='zikr.zikr')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'zikr'), name='unique_user_zikr_count')],
            },
        ),
    ]
