# Generated by Django 5.1.5 on 2026-08-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zikr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zikr',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
