# Generated by Django 5.1.5 on 2026-09-29 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(help_text='Masalan: marta, daqiqa, bet, qadam', max_length=30)),
                ('daily_target', models.PositiveIntegerField(blank=True, help_text="Ixtiyoriy kunlik maqsad — bo'sh qoldirilsa, shunchaki kuzatiladi", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField(default=0)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['habit', 'date'], name='habits_habi_habit_i_e7faa4_idx')],
                'constraints': [models.UniqueConstraint(fields=('habit', 'date'), name='unique_habitlog_per_habit_date')],
            },
        ),
    ]
