# Generated by Django 5.1.5 on 2026-09-30 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(help_text='Masalan: qadam, bet, daqiqa', max_length=30)),
                ('target_count', models.PositiveBigIntegerField()),
                ('current_count', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserCollectiveHabitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('collective_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_counts', to='habits.collectivehabit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collective_habit_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'collective_habit'), name='unique_user_collective_habit_count')],
            },
        ),
    ]
