# Generated by Django 5.1.5 on 2026-09-30 08:52

import apps.habits.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_collectivehabit_usercollectivehabitcount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(help_text='Masalan: qadam, bet, daqiqa', max_length=30)),
                ('target_count', models.PositiveBigIntegerField()),
                ('current_count', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('invite_token', models.CharField(default=apps.habits.models.generate_invite_token, max_length=24, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shared_habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedHabitInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shared_habit_invites', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shared_habit_invites', to=settings.AUTH_USER_MODEL)),
                ('shared_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='habits.sharedhabit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shared_habit', 'invitee'), name='unique_shared_habit_invite')],
            },
        ),
        migrations.CreateModel(
            name='SharedHabitMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('shared_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='habits.sharedhabit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_habit_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shared_habit', 'user'), name='unique_shared_habit_member')],
            },
        ),
    ]
