# Generated by Django 5.1.5 on 2026-07-29 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('bomdod', 'Bomdod'), ('peshin', 'Peshin'), ('asr', 'Asr'), ('shom', 'Shom'), ('xufton', 'Xufton')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('rakat_count', models.PositiveSmallIntegerField(help_text='Hazar holatidagi farz rakat')),
                ('qasr_rakat_count', models.PositiveSmallIntegerField(help_text='Safar (qasr) holatidagi farz rakat')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_goal_per_user_date')],
            },
        ),
        migrations.CreateModel(
            name='InitialQazoSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('consistent', "Muntazam o'qiyman"), ('owes_qazo', 'Qazosi bor')], max_length=20)),
                ('reference_date', models.DateField(help_text='consistent: qachondan beri qoldirmayapti; owes_qazo: qachondan beri qazosi bor')),
                ('manual_override_count', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qazo_setups', to=settings.AUTH_USER_MODEL)),
                ('prayer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayers.prayertype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'prayer_type'), name='unique_setup_per_user_prayer')],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('is_safar', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
                ('prayer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayers.prayertype')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='prayers_dai_user_id_be01e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'prayer_type', 'date'), name='unique_log_per_user_prayer_date')],
            },
        ),
        migrations.CreateModel(
            name='QazoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_missed', models.PositiveIntegerField(default=0)),
                ('total_completed', models.PositiveIntegerField(default=0)),
                ('prayer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayers.prayertype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qazo_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'prayer_type'), name='unique_record_per_user_prayer')],
            },
        ),
    ]
