# Generated by Django 5.1.5 on 2026-07-29 11:27

from django.db import migrations

# (code, name, order, rakat_count, qasr_rakat_count)
PRAYER_TYPES = [
    ("bomdod", "Bomdod", 1, 2, 2),
    ("peshin", "Peshin", 2, 4, 2),
    ("asr", "Asr", 3, 4, 2),
    ("shom", "Shom", 4, 3, 3),
    ("xufton", "Xufton", 5, 4, 2),
]


def seed_prayer_types(apps, schema_editor):
    PrayerType = apps.get_model("prayers", "PrayerType")
    for code, name, order, rakat_count, qasr_rakat_count in PRAYER_TYPES:
        PrayerType.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "order": order,
                "rakat_count": rakat_count,
                "qasr_rakat_count": qasr_rakat_count,
            },
        )


def unseed_prayer_types(apps, schema_editor):
    PrayerType = apps.get_model("prayers", "PrayerType")
    PrayerType.objects.filter(code__in=[p[0] for p in PRAYER_TYPES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_prayer_types, unseed_prayer_types),
    ]
