# Generated by Django 5.1.5 on 2026-07-30 10:54

from django.db import migrations, models


def seed_vitr(apps, schema_editor):
    PrayerType = apps.get_model("prayers", "PrayerType")
    # Vitr (wajib, Hanafi fiqh) also requires qada — same rakat count whether
    # travelling or not, like Bomdod/Shom.
    PrayerType.objects.update_or_create(
        code="vitr",
        defaults={"name": "Vitr", "order": 6, "rakat_count": 3, "qasr_rakat_count": 3},
    )


def unseed_vitr(apps, schema_editor):
    PrayerType = apps.get_model("prayers", "PrayerType")
    PrayerType.objects.filter(code="vitr").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0002_seed_prayer_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialqazosetup',
            name='reference_date',
            field=models.DateField(blank=True, help_text="consistent: qachondan beri qoldirmayapti; owes_qazo: qachondan beri qazosi bor. owes_qazo holatida manual_override_count berilgan bo'lsa ixtiyoriy.", null=True),
        ),
        migrations.AlterField(
            model_name='prayertype',
            name='code',
            field=models.CharField(choices=[('bomdod', 'Bomdod'), ('peshin', 'Peshin'), ('asr', 'Asr'), ('shom', 'Shom'), ('xufton', 'Xufton'), ('vitr', 'Vitr')], max_length=20, unique=True),
        ),
        migrations.RunPython(seed_vitr, unseed_vitr),
    ]
