# Generated by Django 5.1.5 on 2026-07-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0003_alter_initialqazosetup_reference_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='missed_count',
            field=models.PositiveIntegerField(default=0, help_text="Shu kun qoldirilgan (yangi qazo bo'lgan) namozlar soni"),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='completed_count',
            field=models.PositiveIntegerField(default=0, help_text="Shu kun o'qilgan qazolar soni"),
        ),
    ]
