# Generated by Django 5.1.5 on 2026-07-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0004_dailylog_missed_count_alter_dailylog_completed_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialqazosetup',
            name='reference_date',
        ),
        migrations.AlterField(
            model_name='initialqazosetup',
            name='manual_override_count',
            field=models.PositiveIntegerField(blank=True, help_text="owes_qazo holatida taxminiy qazo soni. Berilmasa 0 dan boshlanadi va dashboard'dagi + tugmasi orqali kuzatiladi.", null=True),
        ),
    ]
