# Generated by Django 5.1.5 on 2026-07-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0005_remove_initialqazosetup_reference_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='completed_count',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='is_safar',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='missed_count',
        ),
        migrations.RemoveField(
            model_name='qazorecord',
            name='total_completed',
        ),
        migrations.RemoveField(
            model_name='qazorecord',
            name='total_missed',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='hazar_completed_count',
            field=models.PositiveIntegerField(default=0, help_text="Shu kun oddiy holatda o'qilgan qazo"),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='hazar_missed_count',
            field=models.PositiveIntegerField(default=0, help_text='Shu kun oddiy holatda qoldirilgan'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='qasr_completed_count',
            field=models.PositiveIntegerField(default=0, help_text="Shu kun safarda o'qilgan qazo"),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='qasr_missed_count',
            field=models.PositiveIntegerField(default=0, help_text='Shu kun safarda qoldirilgan'),
        ),
        migrations.AddField(
            model_name='qazorecord',
            name='hazar_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qazorecord',
            name='hazar_missed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qazorecord',
            name='qasr_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qazorecord',
            name='qasr_missed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
