# Generated by Django 5.1.5 on 2026-08-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0006_remove_dailylog_completed_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialqazosetup',
            name='manual_override_count',
        ),
        migrations.AddField(
            model_name='initialqazosetup',
            name='hazar_manual_override_count',
            field=models.PositiveIntegerField(blank=True, help_text='owes_qazo holatida taxminiy oddiy (hazar) qazo soni. Berilmasa 0 dan boshlanadi.', null=True),
        ),
        migrations.AddField(
            model_name='initialqazosetup',
            name='qasr_manual_override_count',
            field=models.PositiveIntegerField(blank=True, help_text='owes_qazo holatida taxminiy safar (qasr) qazo soni. Berilmasa 0 dan boshlanadi.', null=True),
        ),
    ]
