# Generated by Django 5.1.5 on 2026-08-19 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0007_remove_initialqazosetup_manual_override_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TapLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(choices=[('hazar_missed', 'Oddiy qoldirildi'), ('hazar_completed', "Oddiy o'qildi"), ('qasr_missed', 'Safar qoldirildi'), ('qasr_completed', "Safar qazosi o'qildi")], max_length=20)),
                ('prayer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayers.prayertype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tap_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='prayers_tap_user_id_83e2c4_idx')],
            },
        ),
    ]
