# Generated by Django 5.1.5 on 2026-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follower_visibility',
            field=models.CharField(choices=[('full', "To'liq"), ('percent_only', 'Faqat foiz'), ('none', 'Hech narsa')], default='percent_only', max_length=20),
        ),
    ]
