# Generated by Django 5.1.5 on 2026-08-10 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_follower_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Username faqat lotin harflari, raqam va pastki chiziqdan iborat bo'lishi kerak (3-32 belgi).", regex='^[a-zA-Z0-9_]{3,32}$')]),
        ),
    ]
